### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "url" because "this.resourcePack" is null

### ISSUE THREAD

**Issue by PackmanDude** [MinersStudios/WhoMine#6]
https://pastebin.com/tM6vrWKA

**Comment by nykonhrytsyshyn** [comment]
The resourcepack system will soon be completely redone with new functionality, for now any bugs in it are due to the old shitty code and the fact that I disabled loading resourcepacks

**Comment by PackmanDude** [comment]
Understood.
